import React, { memo } from "react";
import type { Metadata } from "next";
import Friends from "./Fridends";

const getFriends = async () => {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API}/friends`, {
    cache: "force-cache",
  });

  return res.json();
};
export const metadata: Metadata = {
  title: "友人帐-Lancao`s",
  description: "Generated by create next app",
};
const page = memo(async () => {
  const list = await getFriends();
  console.log(list);

  return (
    <div>
      <Friends list={list} />
    </div>
  );
});
page.displayName;
export default page;
