import React, { memo } from "react";
import About from "./about";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "关于我-Lancao`s",
  description: "Generated by create next app",
};
const page = memo(() => {
  return (
    <div>
      <About />
    </div>
  );
});
page.displayName;
export default page;
