import React, { memo } from "react";
import Moments from "./Moments";
import type { Metadata } from "next";

const getMoments = async () => {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API}/moments`);

  return res.json();
};
export const metadata: Metadata = {
  title: "动态-Lancao`s",
  description: "Generated by create next app",
};
const page = memo(async () => {
  const list = await getMoments();

  console.log(list);

  return (
    <div>
      <Moments list={list}></Moments>
    </div>
  );
});
page.displayName;
export default page;
