import React from "react";
import Tag from "./Tag";
import type { Metadata } from "next";
const getTag = async (name: string) => {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API}/tag?tagName=${name}`,
    {
      cache: "no-store",
    }
  );

  return res.json();
};
export const metadata: Metadata = {
  title: "标签-Lancao`s",
  description: "Generated by create next app",
};
export default async function Page({ params }: { params: { slug: string } }) {
  const name = decodeURIComponent(params.slug);
  const res = await getTag(name);
  return <Tag name={name} list={res} />;
}
