"use client";
import "@/styles/globals.css";
import { Providers } from "./providers";
// import type { Metadata } from "next";
import AppHeader from "@/components/App-Header/AppHeader";
import AppFotter from "@/components/App-Fotter/AppFotter";
import { WithRedux } from "@/store/withRedux";
import list from "@/assets/data/headerList.json";
import AppMain from "@/components/App-Main/AppMain";
import { Suspense } from "react";
// import Loading from "./loading/loading";

// export const metadata: Metadata = {
//   title: "Blog",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <head>
        <meta
          http-equiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        ></meta>
      </head> */}

      <body>
        <Providers>
          <WithRedux>
            <AppHeader list={list} />
            <AppMain>
              <Suspense fallback={<p>Loading feed...</p>}>{children}</Suspense>
            </AppMain>

            <AppFotter />
          </WithRedux>
        </Providers>
      </body>
    </html>
  );
}
