"use client";
import "@/styles/globals.css";
import { Providers } from "./providers";
// import type { Metadata } from "next";
import AppHeader from "@/components/App-Header/AppHeader";
import AppFotter from "@/components/App-Fotter/AppFotter";
import { WithRedux } from "@/store/withRedux";
import list from "@/assets/data/headerList.json";
import AppMain from "@/components/App-Main/AppMain";
// export const metadata: Metadata = {
//   title: "Blog",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <WithRedux>
            <AppHeader list={list} />
            <AppMain>{children}</AppMain>
            <AppFotter />
          </WithRedux>
        </Providers>
      </body>
    </html>
  );
}
