import React, { memo } from "react";
import Home from "./Home";
import type { Metadata } from "next";

async function getBlogs() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API}/blogs`, {
    cache: "no-store",
  });
  console.log("home blog");

  return res.json();
}

export const metadata: Metadata = {
  title: "首页-Lancao`s",
  description: "Generated by create next app",
};
const page = memo(async () => {
  const { data } = await getBlogs();
  return (
    <div>
      <Home data={data}></Home>
    </div>
  );
});
page.displayName;
export default page;
